version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ovulo_postgres_dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: ovulo_dev
      POSTGRES_USER: ovulo_user
      POSTGRES_PASSWORD: ovulo_password_dev
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - ovulo_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ovulo_user -d ovulo_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  ovulo_network:
    driver: bridge